### ISSUE TITLE
Type 'MyComponent' has no properties in common with type 'Component'.

### ISSUE THREAD

**Issue by kenjinp** [Trixt0r/ecsts#15]
When you implement a Component with extra properties, typescript gets mad because those new properties don't match to the strict Component interface contract. Thus the error `Type 'MyComponent' has no properties in common with type 'Component'.`

![Screenshot from 2020-07-01 10-51-20](https://user-images.githubusercontent.com/5485824/86224166-d3b4a880-bb88-11ea-964a-5e08bdf168cd.png)

A solution might be to add an index property such as shown below, although I'm not sure it's the best solution. 
![Screenshot from 2020-07-01 10-47-51](https://user-images.githubusercontent.com/5485824/86223847-6274f580-bb88-11ea-81db-0bfe2451c715.png)

**Comment by Trixt0r** [comment]
You could actually do something like this

```ts
export interface AnyComponent extends Component {
  [key: string]: any;
}

export class ClientAuthority implements AnyComponent {
  // ... your implementation goes here ...
}
```

I'll add it anyways, to prevent consumers from boilerplate code.
