### ISSUE TITLE
Rename Entity to AbstractEntity?

### ISSUE THREAD

**Issue by delaneyj** [Trixt0r/ecsts#3]
Since you have to extend anyways (<3 that) it would be cleaner to be able to write

```
export default class Entity extends AbstractEntity {
  constructor(id?: number) {
   ...
  }
```

**Comment by Trixt0r** [comment]
Ran into this issue, too. I renamed the class directly in the `import` statement.
Will consider renaming it...

**Comment by delaneyj** [comment]
Great I did the same but seemed like an anti-pattern, do you want me to close this or leave as a reminder?

**Comment by Trixt0r** [comment]
Please leave it, I will close it with the next commit.
