### ISSUE TITLE
Type error when getting component in a system

### ISSUE THREAD

**Issue by amireldor** [Trixt0r/ecsts#37]
I think there is something funny with the `Component` interface type and my specific TypeScript version.

I defined a component of `HasLifeforce` and a `LifeforceSystem` system.

In my system, when I try to get components by their types, I get the following error:

```typescript
// system
      const lifeforce = entity.components.get<HasLifeforce>(HasLifeforce);
    // the (HasLifeforce) in parenthesis is marked
```

```
Argument of type 'typeof HasLifeforce' is not assignable to parameter of type 'string | ComponentClass<HasLifeforce>'.
  Type 'typeof HasLifeforce' is not assignable to type 'ComponentClass<HasLifeforce>'.
    Types of parameters 'lifeforce' and 'args' are incompatible.
      Type 'unknown' is not assignable to type 'number | undefined'.
        Type 'unknown' is not assignable to type 'number'.
```

I'm using:
```
    "typescript": "^4.5.3"
```

I define my component similar to your example with and get the error:

```typescript
import { Component } from "@trixt0r/ecs";

export class HasLifeforce implements Component {
  constructor(public lifeforce: number = 0) {}
}
```

Yet if I write it as the following, the error in the system does not pop up and the typing is fine.

```typescript
import { Component } from "@trixt0r/ecs";

export class HasLifeforce implements Component {
  lifeforce = 0;
}
```

![image](https://user-images.githubusercontent.com/1746811/150561313-6ba22593-4885-437f-8e24-ffc646367513.png)

Any ideas? I'll try to make a reproducible example.
The transpiled code works either way.

**Comment by Trixt0r** [comment]
Thanks for reporting this issue!

~~Fixed in v0.4.5~~
Fixed in [v0.4.6](https://github.com/Trixt0r/ecsts/releases/tag/v0.4.6)
