### ISSUE TITLE
Getting an entity directly by its id

### ISSUE THREAD

**Issue by amireldor** [Trixt0r/ecsts#38]
Hello. How do you feel about getting entities by ids?
I have something like this when I want to find a planet in my game with a specific id.

```typescript
this.engine.entities.find((x) => x.id === planetId) ?? null;
```

I looked at your code for `Collection` and it's rather type-agnostic and keeps the elements in an array. If it "knew" it holds elements with an id, like entities, it could store them in a map/dict and we could fetch those instantly instead of `.find`ing through the entire collection.

Thinking about this, I thought maybe listening to an "onAdded" event _somewhere_ and track id->entity somehow in my own code, but it would be nice to have this in the library-level.

Is that possible? Does it accidentally break the data-driven nature of ECS possible optimizations?
I'd be happy to hear your input. Thanks for the cool library.

**Comment by Trixt0r** [comment]
Hi

Thanks for your input.

Yes, I had something like this in mind, a long time ago.

For my purposes I am managing a map of entities on my app specific code. The `onAdded` is used there, as you described.

A component collection already implements such a caching mechanism (but for type lookups).

I think, if at least one user of this library can benefit of such an improvement, I should implement it.
But I have to think about a naive implementation, which just uses the `id` or a more extensible version.

**Comment by amireldor** [comment]
Thank you for your response :) I'll keep following on this.

If you feel you need help or you don't have enough time for this I can try making a pull request. I'll attempt to keep the code standard high (good work on your side!). Do you have any technical direction you were thinking to approach this?

**Comment by Trixt0r** [comment]
I think a first valid approach would be to create an entity collection which extends the base collection and implements the caching part. Would be quite similar to what the component collection already does.

Feel free to make a pull request of course.

**Comment by amireldor** [comment]
Hi @Trixt0r, thanks for implementing the feature 🎉
I'll get to using it in a week or so in my project. Thanks.
