### ISSUE TITLE
Consider changing Filter to Aspect

### ISSUE THREAD

**Issue by delaneyj** [Trixt0r/ecsts#4]
Its wonderful that you have component filtering.  Usually in ECS parlance this is called an Aspect.  Unfortunately filter is super overloaded in games for effects especially.

**Comment by Trixt0r** [comment]
Yes, I also wondered if `Filter` is a good name, while implementing it.
I though it would fit since it _filters_ by component types.
`Aspect` seems to be fine but I will have a look into other `ECS` implementations first before renaming it. :)

**Comment by delaneyj** [comment]
In general aspects is basically a set of filters.  Right now you are saying get all of an array, but you also might want all of X and Y but not if Z (like a hide component).

**Comment by Trixt0r** [comment]
Yes, I see. Defining more detailed queries could be very useful.
I saw such filtering features in the ECS of MonoGame. Will have a look...

**Comment by delaneyj** [comment]
Artemis has a decent Aspect framework, the syntax isn't great due to Java but the core is solid.
