### ISSUE TITLE
Spatial/geo/area separation of entities, am I doing it right?

### ISSUE THREAD

**Issue by amireldor** [Trixt0r/ecsts#42]
Hi. I want to make some kind of 'spatial' separation of my entities and wondering if my approach is sane.

Background: my game is set in space with multiple star systems, where in each star you have planet and ship entities. I have a system for telling ships where to fly next and I want their destinations to only be planets of the same star system.

I created a class called `MappedEntitiesAspectListener` implementing `AspectListener` that listens to additions and removals of entities from the engine. The class is given a custom mapper function for mapping entities to different keys based on *whatever*. Additionally, you can get the entities collected by this class given the mapped key.

This is an example demonstrating the functionality, please let me know if it's sane. If it is, and you wish, I will create a PR with a cleaner example for your examples folder.

```ts
import { nanoid } from "nanoid";
import {
  Component,
  Engine,
  AbstractEntity,
  EntityCollection,
  AspectListener,
  EntityListener,
} from "@trixt0r/ecs";

class InStar implements Component {
  constructor(public starId: number) {}
}

class MyEntity extends AbstractEntity {
  constructor() {
    super(nanoid(6));
  }
}

class PlanetEntity extends MyEntity {
  constructor(starId: number) {
    super();
    this.components.add(new InStar(starId));
  }
}

const engine = new Engine();

class MappedEntitiesAspectListener<Key> implements AspectListener {
  constructor(protected mapperFn: (entity: AbstractEntity) => Key) {}

  private mapping = new Map<Key, EntityCollection>();

  getByKey(key: Key): EntityCollection | undefined {
    return this.mapping.get(key);
  }

  onAddedEntities(
    ...entities: AbstractEntity<Component, EntityListener<Component>>[]
  ): void {
    entities.forEach((entity) => {
      const key = this.mapperFn(entity);
      if (this.mapping.has(key)) {
        this.mapping.get(key)!.add(entity);
      } else {
        this.mapping.set(key, new EntityCollection([entity]));
      }
    });
  }

  onRemovedEntities(
    ...entities: AbstractEntity<Component, EntityListener<Component>>[]
  ): void {
    entities.forEach((entity) => {
      const key = this.mapperFn(entity);
      this.mapping.get(key)?.remove(entity);
    });
  }
}

const entitiesByStarId = new MappedEntitiesAspectListener((entity) => {
  const inStar = entity.components.get(InStar);
  return inStar ? inStar.starId : undefined;
});

engine.addListener(entitiesByStarId);
const somePlanet = new PlanetEntity(1);

engine.entities.add(somePlanet);
engine.entities.add(new PlanetEntity(1));
engine.entities.add(new PlanetEntity(1));
engine.entities.add(new PlanetEntity(2));
engine.entities.add(new PlanetEntity(2));
engine.entities.add(new PlanetEntity(3));
engine.entities.add(new PlanetEntity(4));
engine.entities.add(new PlanetEntity(4));
engine.entities.add(new PlanetEntity(4));
engine.entities.add(new PlanetEntity(4));

function showPlanetsForStarId(starId: number) {
  const planets = entitiesByStarId.getByKey(starId);
  console.log(
    `Star ${starId} has ${planets?.length} planets`,
    planets?.map((entity) => {
      return entity.id;
    })
  );
}

showPlanetsForStarId(1);
showPlanetsForStarId(2);
showPlanetsForStarId(3);
showPlanetsForStarId(4);
console.log("removing some planet");
engine.entities.remove(somePlanet);
showPlanetsForStarId(1);
```

Example output:
![image](https://github.com/Trixt0r/ecsts/assets/1746811/33ae9791-6906-4815-97e6-bef0641472aa)

**Comment by Trixt0r** [comment]
Hi Amir

Sorry for the delayed response.

I think designing the relation between planet and star by using a dedicated component is fine.

IMO a custom aspect listener isn't even needed. The default implementation of the aspect listener already supports the optional `id` field on the `Component` interface.

You could change `public starId: number` on `InStar` to `public id: string` and instantiate aspects for each star on your engine:

```ts
const stars = [
  Aspect.for(engine).all({ id: String(1) }),
  Aspect.for(engine).all({ id: String(2) }),
  Aspect.for(engine).all({ id: String(3) }),
  Aspect.for(engine).all({ id: String(4) }),
]

stars.forEach((star, i) => /* log stuff */);
```

But it depends of course on your game's needs and the stars need to have a more descriptive identifier.

I saw that the documentation of the library is not up-to-date. It only mentions component types but no ids.

Maybe you can create an example on stackblitz or codesandbox for this case?

Thanks for using the library.

**Comment by amireldor** [comment]
Hi @Trixt0r, thanks for the answer.

Does the default aspect only works with a property called `id`? I'll try creating an example for this as you suggested to try it out.

**Comment by amireldor** [comment]
https://stackblitz.com/edit/typescript-zn8wvp?file=index.ts

**Comment by Trixt0r** [comment]
Yes, that looks good.

The default aspect implementation works only with `id` and `type`.

**Comment by amireldor** [comment]
I got my answer so I will close this to reduce the open issues count. Thanks for the library.
