### ISSUE TITLE
OnComponentAdded/Removed at the system level?

### ISSUE THREAD

**Issue by delaneyj** [Trixt0r/ecsts#5]
I have a situation where I have init and cleanup at the system level when a component is added to an entity.  Can do in `process` but it gets run every frame.  Would be ideal to have as a dispatched event at the engine &&|| system level.

**Comment by Trixt0r** [comment]
You can let your systems register those listeners during `onAddedToEngine`.

So you would basically do something like this:
```ts
class MySystem extends System {

  // ...

  onAddedToEngine(engine: Engine): void {
    // ...
    engine.addListener({
      onAddedEntities: entities => {
          entities.forEach(entity => {
            entity.addListener({
              onAddedComponents: components => {
                // Do you logic here
              }
            })
          })
      }
    });
  }
}
```

**Comment by delaneyj** [comment]
Yes that could work.   I was wondering if System's should by default have an Array<Aspect/Filter> built in the constructor.  If its empty nothing from current behavior changes, however it would handle the onAdded/Removed component cases elegantly.  If filters https://github.com/Trixt0r/ecsts/issues/4  was change to chain-able filters.  It seems like there is a lot of boilerplate in more real world systems that could be avoided.

**Comment by delaneyj** [comment]
Actually wouldn't it be ``` engine.addListener({
      onAddedEntities: e => {
        e.addListener({
          onAddedComponents: c => {...```?  I'm also seeing the dispatcher isn't using promises so can get into a state where system process can happen before the init/loading occurs.

**Comment by Trixt0r** [comment]
I guess having optional aspects in the constructor makes more sense than defining each system as an `EntityListener` by default, since each implementation will filter entities anyway and reusability of those aspects would be more clear in the code.

> Actually wouldn't it be ` engine.addListener({ onAddedEntities: e => { e.addListener({ onAddedComponents: c => {...`?

You are right.

Thanks for the input!

**Comment by delaneyj** [comment]
No problem, you might have been able to tell I'm actively trying to use it on a project :+1:
