### ISSUE TITLE
Question: Aspects as Dispatcher?

### ISSUE THREAD

**Issue by delaneyj** [Trixt0r/ecsts#7]
As previously talked about now that all Systems have an aspect could you have lifecycle events on the Aspect?  Stuff like added/removed component/entity.

**Comment by Trixt0r** [comment]
Can you write down a use case for this?

**Comment by delaneyj** [comment]
Absolutely.  So I have a menu system and a renderer.  When you create a logical button there is setup of the graphics elements and teardown/disposal on remove.  I tried what we talked about before basically ```onAddedToEngine() {
    this.engine.addListener({
      onAddedEntities: e => {
        const id = e.id as number;

        e.addListener({
          onAddedComponents: c => {
            debugger;
            switch (c.constructor) {
              case RectangleComponent:
                console.log("add rect");
                const gfx = new Graphics();
                gfx.name = e.id.toString();
                this.containers.set(id, gfx);
                this.app.stage.addChild(gfx);
                break;```

However any any system this boilerplate with have to be there for the setup and teardown.  You could try to do during the process step but you don't as far as I know have info about the component being added/removed at that time.  Your rectangles example doesn't deal with removing and adding entities on the fly based on interaction which could help show the issues.  I don't really care if the hook is on the system or aspect but just like you have `onAddedToEngine` there should be `onComponentAdded<T>/Removed<T>` available to hook into.

**Comment by Trixt0r** [comment]
I see. Have to think about if dispatching on aspect level would be better than on system level. Both options make sense...

I will have a look into this tomorrow.
