### ISSUE TITLE
Consider using integer for ID

### ISSUE THREAD

**Issue by delaneyj** [Trixt0r/ecsts#8]
Starting a bigger project and constantly casting the `id: to string|number`.  The id is suppose to be more like a primary key and used for fast lookups.  Especially in es6 maps the lookup speed of integers versus string when used constantly is dramatic.  If strings are needed they are better placed in Tag/Debug components.

**Comment by Trixt0r** [comment]
Well, I need global unique ids in a project, therefore ids have to have the option of being a string.

You could define your own abstract entity which defines all ids as a number.

I don't see the problem here.

**Comment by Trixt0r** [comment]
Besides... if you only use numbers instead of strings, it won't have any negative performance impacts at runtime. Even if the id is typed as `string | number`.
